language: node_js

node_js:
  - "12"

dist: trusty

# Trigger build only when one of the following conditions is met
if: type = pull_request OR branch = master OR tag IS present

addons:
  chrome: stable
  sonarcloud:
    organization: "ontotext-ad"
  # Needed for Cypress tests
  apt:
    packages:
      - libgconf-2-4


## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache

script:
  - npm run lint
  - npm run test
  - npm run cy:ci
  - npm run build:prod

deploy:
  - provider: npm
    skip_cleanup: true
    email:  $NPM_MAIL
    api_key: $NPM_TOKEN
    on:
      tags: true

  - provider: script
    script: npm run build:prod
