language: node_js

node_js:
  - "12"

dist: trusty

# Trigger build only when one of the following conditions is met
if: type = pull_request OR branch = master OR tag IS present

addons:
  chrome: stable
  sonarcloud:
    organization: "ontotext-ad"
  # Needed for Cypress tests
  apt:
    packages:
      - libgconf-2-4


## Cache NPM folder and Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.npm
    - ~/.cache

#before_script:
#  ## runs the 'start' script which
#  ## boots our local app server on port 4200
#  ## which cypress expects to be running
#  ## -----------------------------------
#  ## we use the '&' ampersand which tells
#  ## travis to run this process in the background
#  ## else it would block execution and hang travis
#  - npm run start

script:
  - npm run lint
  - npm run test
  - npm run start
  - npm run cy:run
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email:  $NPM_MAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
