export enum ChannelName {
  UpdateMapping = 'update_mapping',
  SaveMapping = 'save_mapping',
  MappingSaved = 'mapping_saved',
  RDFGenerated = 'rdf_generated',
  SparqlGenerated = 'sparql_generated',
  NewMapping = 'new_mapping',
  ViewMode = 'view_mode',
  GetRDF = 'get_RDF',
  GetSPARQL = 'sparql',
  DirtyMapping = 'dirty_mapping',
  ProgressCancelled = 'progress_cancelled',
  GetJSONMapping = 'get_json_mapping',
  DownloadSparql = 'download_sparql',
  DownloadRdf = 'download_rdf',
  DownloadCompleted = 'downloaded_completed',
  GenerateSparql = 'generate_sparql',
  SparqlGenerationCompleted = 'sparql_generation_completed',
  SwitchRenderingMode = 'switch_rendering_mode',
  RenderingModeSwitched = 'rendering_mode_switched',
  SwitchEditorOrientation = 'switch_editor_orientation',
  EditorOrientationSwitched = 'editor_orientation_switched',
  SaveEditorConfiguration = 'save_editor_configurations',
  EditorConfigurationSaveCompleted = 'editor_configurations_save_completed',
  OpenInGdb = 'open_in_gdb',
  EditorConfigurationChanged = 'editor_configuration_changed'
}
